### ISSUE TITLE
page.prev和page.next获取的值相反

### ISSUE THREAD

**Issue by i2Echo** [viosey/hexo-theme-material#288]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

使用本主题后，翻页上一篇下一篇正好相反（按时间排序），即prev为旧的时间节点文章，next为新的时间节点文章了，按照正常习惯是prev为新的时间节点文章，next为旧的时间节点。我暂时是将post-nav.ejs文件下的顺序换过来，但是我看hexo文档是按照正常顺序（page.prev获取上一篇【新】，page.next获取下一篇【旧】）来的没错的，不知道为什么我的会出现相反的现象，还有顺便问一下如何去调试hexo的这些变量，谢谢！

**Comment by neoFelhz** [comment]
Yep. It caused by hexo 3.2.2 or newer.

**Comment by NoahDragon** [comment]
https://github.com/hexojs/hexo/issues/2474 https://github.com/hexojs/hexo/pull/2262
It should be fixed in Hexo 3.3.1.

**Comment by Halyul** [comment]
@NoahDragon but last night I have tested on hexo 3.3.1, it seems that the issue is still there

**Comment by NoahDragon** [comment]
@Halyul you are right, seem the fix is not working.

**Comment by i2Echo** [comment]
@NoahDragon yeap, is to updated the hexo to the latest version 3.3.1, that the issue  was happend.

**Comment by i2Echo** [comment]
@NoahDragon yeap, is to updated the hexo to the latest version 3.3.1, that the issue  was happend.

**Comment by NoahDragon** [comment]
The hexo have reverted the changes for the sort fix. https://github.com/hexojs/hexo/pull/2526

**Comment by neoFelhz** [comment]
I have just updated the hexo to 3.3.5 and found the problem solved.
